server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kanbanBoard?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: purkal#ananya9@8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: user-authentication-service
erureka:
 cleint:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  hostname: localhost






# just for tempo  purkal#ananya9@8