server:
 port: 8086
spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/kanbanBoard
 application:
  name: user-profile-service
erureka:
 cleint:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  hostname: localhost